Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 8083, host: 8083
  config.vm.network "forwarded_port", guest: 2003, host: 2003
  config.vm.synced_folder "../user-registration-application/target", "/target", create: true


  config.vm.provision "docker" do |d|
    d.build_image "--tag=ubuntu-update /vagrant/ubuntu-update"
    d.build_image "--tag=user-registration /vagrant/user-registration"
    d.build_image "--tag=graphite /vagrant/graphite"
  end
  config.vm.provision "docker", run: "always" do |d|d.run "graphite",
      args: "-p 8082:80 -p 2003:2003"
    d.run "user-registration",
      args: "-p 8083:8080 -v /target:/target --link graphite:graphite"
  end

end
